#!/usr/bin/env python

import os
import sys

import torch
from diffusers import StableDiffusionPipeline

os.makedirs("diffusers-cache", exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    "darkstorm2150/Protogen_v2.2_Official_Release",
    cache_dir="diffusers-cache",
)
